<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<!-- A project that uses aweXpect instead of TUnit's assertions references the engine without `TUnit.Assertions`. -->
	<ItemGroup>
		<PackageReference Include="TUnit.Engine"/>
		<PackageReference Include="Microsoft.Testing.Extensions.TrxReport"/>
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Source\aweXpect.Generators\aweXpect.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
		<ProjectReference Include="..\..\..\Source\aweXpect\aweXpect.csproj"/>
	</ItemGroup>

</Project>
