using System.Text;

namespace aweXpect.SourceGenerators.Helpers;

internal static class CollectionExpectationSources
{
	public const string Attribute =
		"""
		// <auto-generated />
		using System;

		namespace aweXpect.SourceGenerators;

		#nullable enable
		/// <summary>
		/// Create the overloads of a collection expectation from the annotated helper, which holds the body.
		/// </summary>
		/// <remarks>
		/// The helper's signature is the declaration: its return type, its subject and expected parameters and its
		/// type parameters are emitted verbatim, and a helper behind an <c>#if</c> generates nothing where it does
		/// not exist. Only what the signature cannot state belongs here.
		/// </remarks>
		[System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = true)]
		// The generator reads the attributes from the source, so the never-defined symbol keeps them out of the assembly.
		[System.Diagnostics.Conditional("AWEXPECT_SOURCE_GENERATOR")]
		internal class CreateCollectionExpectationAttribute : System.Attribute
		{
			/// <param name="name">The expectation name, where <c>{Not}</c> marks the negated variant.</param>
			public CreateCollectionExpectationAttribute(string name)
			{
				Name = name;
			}

			public string Name { get; }

			/// <summary>
			/// The class whose parameterless <c>Create*</c> methods define the supported element types. Each nullable
			/// element additionally yields an overload taking a non-nullable expected collection.
			/// </summary>
			public Type? Factory { get; set; }

			/// <summary>
			/// The expected parameter type, when it differs from the helper's second parameter. <c>{subject}</c>
			/// stands for the subject collection type and <c>{item}</c> for its element.
			/// </summary>
			public string? ExpectedType { get; set; }

			/// <summary>
			/// Emit this family once per collection type listed in <c>[CollectionSubjects]</c> on the containing
			/// class, substituting the helper's <c>TCollection</c>.
			/// </summary>
			public bool PerSubject { get; set; }

			/// <summary>Mark the overloads with <c>[GuaranteesNotNull]</c>.</summary>
			public bool GuaranteesNotNull { get; set; }

			/// <summary>
			/// Emit the expected parameter as a <c>params</c> array of <c>ExpectedType</c>, or of the helper's element
			/// type. Such an overload has no single caller expression, so the helper is passed <c>null</c> for it and
			/// formats the value itself.
			/// </summary>
			public bool Params { get; set; }

			/// <summary>The negated name, when it is not the <c>{Not}</c> form of <c>Name</c>.</summary>
			public string? NegatedName { get; set; }

			/// <summary>The <c>OverloadResolutionPriority</c>, or <c>0</c> for none.</summary>
			public int Priority { get; set; }

			public string? Summary { get; set; }
			public string? NegatedSummary { get; set; }
			public string? Remarks { get; set; }
			public string? NegatedRemarks { get; set; }
		}

		/// <summary>
		/// The collection types of this class that need their own overloads - value types such as
		/// <c>ImmutableArray&lt;T&gt;</c> that cannot reach an expectation through the covariance of
		/// <c>IThat&lt;out T&gt;</c>, or kinds whose result keeps the concrete subject type. Adding one here adds it to
		/// every <c>PerSubject</c> family of the class; a type that does not exist in the current compilation is
		/// skipped, and the constraints of its own type parameters carry over to the overloads.
		/// </summary>
		[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true)]
		[System.Diagnostics.Conditional("AWEXPECT_SOURCE_GENERATOR")]
		internal class CollectionSubjectsAttribute : System.Attribute
		{
			/// <param name="collectionTypes">
			/// The collection types, where <c>{item}</c> marks the element; any other type argument names a type
			/// parameter of the helper.
			/// </param>
			public CollectionSubjectsAttribute(params string[] collectionTypes)
			{
				CollectionTypes = collectionTypes;
			}

			public string[] CollectionTypes { get; }

			/// <summary>The <c>OverloadResolutionPriority</c> of these kinds, or <c>0</c> for the family's.</summary>
			public int Priority { get; set; }

			/// <summary>The reason for these kinds' priority, added to the remarks of every overload.</summary>
			public string? Remarks { get; set; }
		}
		#nullable disable
		""";

	public static string GenerateExtensionClass(List<CollectionExpectationFamily> families)
	{
		CollectionExpectationFamily first = families[0];
		StringBuilder builder = new();
		builder.AppendLine("// <auto-generated />");
		builder.Append("namespace ").Append(first.Namespace).AppendLine(";").AppendLine();
		builder.AppendLine("#nullable enable");
		// The generated header keeps the other analyzers out, but the public API analyzer looks at generated code on
		// purpose and the .editorconfig severities do not reach it there, so the repo-wide decision on the
		// optional-parameter back-compat rule has to be restated here.
		builder.AppendLine("#pragma warning disable RS0026");
		builder.Append("public static partial class ").AppendLine(first.ClassName);
		builder.AppendLine("{");
		builder.AppendLine(string.Join("\n\n", families.SelectMany(x => x.Methods)));
		builder.AppendLine("}");
		builder.AppendLine("#nullable disable");
		return builder.ToString();
	}
}
