using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using aweXpect.Core.Metadata;
using aweXpect.Equivalency;

namespace aweXpect.Core.Tests.Equivalency;

public sealed partial class EquivalencyComparisonTests
{
	[Test]
	public async Task WhenCollectionIsAnIterator_ShouldNotCompareItsCapturedState()
	{
		object actual = Iterate(1, 2);
		object expected = Iterate(1, 3);

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), new StringBuilder());

		await That(result).IsTrue()
			.Because("the public fields of an iterator are generated by the compiler to capture its arguments");
	}

	[Test]
	public async Task WhenCollectionOverridesAMemberOfAFrameworkCollection_ShouldNotCompareIt()
	{
		object actual = new FlaggedList(true);
		object expected = new FlaggedList(false);

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), new StringBuilder());

		await That(result).IsTrue()
			.Because("an overridden member is still the member that the framework collection declared");
	}

	[Test]
	public async Task WhenDictionaryTypeHasADifferentOwnMember_ShouldReportItAfterTheEntries()
	{
		object actual = new NamedLookup
		{
			Name = "a",
			["x"] = 1,
		};
		object expected = new NamedLookup
		{
			Name = "b",
			["x"] = 2,
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Element [x] differed:
		                                                      Actual: 1
		                                                    Expected: 2
		                                                and
		                                                  Property Name differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                """).IgnoringNewlineStyle();
	}

	[Test]
	public async Task WhenDictionaryTypeHasEqualOwnMembers_ShouldSucceed()
	{
		object actual = new NamedLookup
		{
			Name = "a",
			["x"] = 1,
		};
		object expected = new NamedLookup
		{
			Name = "a",
			["x"] = 1,
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsTrue();
		await That(failureBuilder.ToString()).IsEmpty();
	}

	[Test]
	public async Task WhenDictionaryTypeImplementsTheInterfaceItself_ShouldOnlyCompareItsOwnMembers()
	{
		object actual = new SelfMadeLookup("a", 3, new Dictionary<string, int>
		{
			["x"] = 1,
		});
		object expected = new SelfMadeLookup("b", 4, new Dictionary<string, int>
		{
			["x"] = 1,
		});
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Property Name differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                """).IgnoringNewlineStyle()
			.Because("Count, Keys and Values implement members of the framework interface, so they describe the entries");
	}

	[Test]
	public async Task WhenExpectedCollectionTypeHasAnOwnMember_AndActualIsAnotherCollectionType_ShouldReportItAsMissing()
	{
		object actual = new List<int>
		{
			1,
			2,
		};
		object expected = new NamedList
		{
			1,
			2,
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Property Name was missing on the actual object
		                                                """).IgnoringNewlineStyle()
			.Because("the members to compare come from the expected object, as for any other object");
	}

	[Test]
	public async Task WhenExpectedCollectionTypeHasAnOwnMember_AndActualTypeHasItToo_ShouldCompareIt()
	{
		object actual = new SelfMadePage<int>("a", 0, 1, 2);
		object expected = CreateNamedList("b", 1, 2);
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Property Name differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                """).IgnoringNewlineStyle();
	}

	[Test]
	public async Task WhenExpectedIsACollectionOfTheFramework_AndActualTypeHasAnOwnMember_ShouldOnlyCompareTheItems()
	{
		object actual = CreateNamedList("a", 1, 2);
		object expected = new[]
		{
			1, 2,
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsTrue()
			.Because("the expected type has no members of its own that could be compared");
		await That(failureBuilder.ToString()).IsEmpty();
	}

	[Test]
	public async Task WhenGetterOfAnOwnMemberThrows_ShouldFailWithTheGetterException()
	{
		ThrowingList actual = new("getter failed");
		ThrowingList expected = new("getter failed");

		async Task Act()
			=> await That(actual).IsEquivalentTo(expected);

		await That(Act).Throws<FailException>()
			.WithMessage("""
			             Expected that actual
			             is equivalent to expected,
			             but Name did throw an InvalidOperationException:
			               getter failed

			             Equivalency options:
			              - include public fields and properties
			             """).And
			.Whose(e => e.InnerException, i => i.Is<InvalidOperationException>());
	}

	[Test]
	public async Task WhenListTypeHasADifferentOwnField_ShouldReportIt()
	{
		object actual = new TaggedList
		{
			Tag = "a",
		};
		object expected = new TaggedList
		{
			Tag = "b",
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Field Tag differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                """).IgnoringNewlineStyle();
	}

	[Test]
	public async Task WhenListTypeHasADifferentOwnField_WithoutFields_ShouldSucceed()
	{
		object actual = new TaggedList
		{
			Tag = "a",
		};
		object expected = new TaggedList
		{
			Tag = "b",
		};
		EquivalencyOptions options = new()
		{
			Fields = IncludeMembers.None,
		};

		bool result = await EquivalencyComparison.Compare(actual, expected, options, new StringBuilder());

		await That(result).IsTrue();
	}

	[Test]
	public async Task WhenListTypeHasADifferentOwnMember_AndAnItemDiffers_ShouldReportTheItemFirst()
	{
		object actual = CreateNamedList("a", 1, 2);
		object expected = CreateNamedList("b", 1, 3);
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Element [1] differed:
		                                                      Actual: 2
		                                                    Expected: 3
		                                                and
		                                                  Property Name differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                """).IgnoringNewlineStyle();
	}

	[Test]
	public async Task WhenListTypeHasADifferentOwnMember_InAnyOrder_ShouldReportIt()
	{
		object actual = CreateNamedList("a", 1, 2);
		object expected = CreateNamedList("b", 2, 1);
		EquivalencyOptions options = new()
		{
			IgnoreCollectionOrder = true,
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, options, failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Property Name differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                """).IgnoringNewlineStyle()
			.Because("the order only concerns the items");
	}

	[Test]
	public async Task WhenListTypeHasADifferentOwnMember_InsideACollection_ShouldReportItWithTheIndex()
	{
		object actual = new object[]
		{
			new NamedList
			{
				Name = "a",
			},
		};
		object expected = new object[]
		{
			new NamedList
			{
				Name = "b",
			},
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Property [0].Name differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                """).IgnoringNewlineStyle();
	}

	[Test]
	public async Task WhenListTypeHasADifferentOwnMember_InsideAnObject_ShouldReportItWithThePath()
	{
		var actual = new
		{
			Value = CreateNamedList("a"),
		};
		var expected = new
		{
			Value = CreateNamedList("b"),
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Property Value.Name differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                """).IgnoringNewlineStyle();
	}

	[Test]
	public async Task WhenListTypeHasADifferentOwnMember_ShouldReportIt()
	{
		object actual = new NamedList
		{
			Name = "a",
		};
		object expected = new NamedList
		{
			Name = "b",
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Property Name differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                """).IgnoringNewlineStyle();
	}

	[Test]
	public async Task WhenListTypeHasADifferentOwnMember_WhenItIsIgnored_ShouldSucceed()
	{
		object actual = new NamedList
		{
			Name = "a",
		};
		object expected = new NamedList
		{
			Name = "b",
		};
		EquivalencyOptions options = new()
		{
			MembersToIgnore = [new MemberToIgnore.ByName("Name"),],
		};

		bool result = await EquivalencyComparison.Compare(actual, expected, options, new StringBuilder());

		await That(result).IsTrue();
	}

	[Test]
	public async Task WhenListTypeHasADifferentOwnMember_WhenItsTypeIsComparedByValue_ShouldUseItsEquals()
	{
		object actual = new NamedList
		{
			Name = "a",
		};
		object expected = new NamedList
		{
			Name = "b",
		};
		EquivalencyOptions options = new EquivalencyOptions().For<NamedList>(o => o with
		{
			ComparisonType = EquivalencyComparisonType.ByValue,
		});
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, options, failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).DoesNotContain("Name")
			.Because("the list does not override Equals, so the instances differ as a whole");
	}

	[Test]
	public async Task WhenListTypeHasADifferentOwnMember_WithoutProperties_ShouldSucceed()
	{
		object actual = new NamedList
		{
			Name = "a",
		};
		object expected = new NamedList
		{
			Name = "b",
		};
		EquivalencyOptions options = new()
		{
			Properties = IncludeMembers.None,
		};

		bool result = await EquivalencyComparison.Compare(actual, expected, options, new StringBuilder());

		await That(result).IsTrue();
	}

	[Test]
	public async Task WhenListTypeHasADifferentOwnMember_WithoutPropertiesForItsType_ShouldSucceed()
	{
		var actual = new
		{
			Value = CreateNamedList("a"),
		};
		var expected = new
		{
			Value = CreateNamedList("b"),
		};
		EquivalencyOptions options = new EquivalencyOptions().For<NamedList>(o => o with
		{
			Properties = IncludeMembers.None,
		});

		bool result = await EquivalencyComparison.Compare(actual, expected, options, new StringBuilder());

		await That(result).IsTrue()
			.Because("the options of the collection type apply to its own members");
	}

	[Test]
	public async Task WhenListTypeHasAnInternalOwnMember_ShouldOnlyCompareItWithInternalProperties()
	{
		object actual = new NamedList
		{
			Revision = 1,
		};
		object expected = new NamedList
		{
			Revision = 2,
		};
		EquivalencyOptions options = new()
		{
			Properties = IncludeMembers.Public | IncludeMembers.Internal,
		};
		StringBuilder failureBuilder = new();

		bool resultWithPublic = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(),
			new StringBuilder());
		bool result = await EquivalencyComparison.Compare(actual, expected, options, failureBuilder);

		await That(resultWithPublic).IsTrue();
		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Property Revision differed:
		                                                      Actual: 1
		                                                    Expected: 2
		                                                """).IgnoringNewlineStyle()
			.Because("the internal members of the framework list, such as its version, are still left out");
	}

	[Test]
	public async Task WhenListTypeHasEqualOwnMembers_ShouldSucceed()
	{
		object actual = CreateNamedList("a", 1, 2);
		object expected = CreateNamedList("a", 1, 2);
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsTrue();
		await That(failureBuilder.ToString()).IsEmpty();
	}

	[Test]
	public async Task WhenListTypeHasMembersOnItsBaseType_ShouldCompareTheMembersOfBothTypes()
	{
		object actual = new DescribedList
		{
			Name = "a",
			Description = "c",
		};
		object expected = new DescribedList
		{
			Name = "b",
			Description = "d",
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Property Description differed:
		                                                      Actual: "c"
		                                                    Expected: "d"
		                                                and
		                                                  Property Name differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                """).IgnoringNewlineStyle();
	}

	[Test]
	public async Task WhenListTypeHidesAMemberOfTheFrameworkList_ShouldCompareIt()
	{
		object actual = new RecountingList
		{
			Count = 1,
		};
		object expected = new RecountingList
		{
			Count = 2,
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Property Count differed:
		                                                      Actual: 1
		                                                    Expected: 2
		                                                """).IgnoringNewlineStyle()
			.Because("a member that hides one of the framework list is declared by the type itself");
	}

	[Test]
	public async Task WhenListTypeIsRegisteredAsACollection_AndExpectedIsNoCollection_ShouldReflectOverAllMembers()
	{
		RegisterShoutingList();
		RegisteredList actual = new()
		{
			Name = "a",
		};
		actual.Add(1);
		var expected = new
		{
			Count = 1,
			Name = "a",
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare<object, object>(actual, expected, new EquivalencyOptions(),
			failureBuilder);

		await That(result).IsTrue()
			.Because("only the members of its own are registered for a collection, which is not all a comparison with another object needs");
		await That(failureBuilder.ToString()).IsEmpty();
	}

	[Test]
	public async Task WhenListTypeIsRegisteredAsACollection_AndHasAField_ShouldCompareTheRegisteredField()
	{
		TypeMetadataRegistry.RegisterBatch(() =>
		{
			TypeMetadataRegistry.RegisterField<RegisteredTaggedList, string>(nameof(RegisteredTaggedList.Tag),
				o => o.Tag.ToUpperInvariant() + "!");
			TypeMetadataRegistry.RegisterCollection<RegisteredTaggedList>();
		});
		object actual = new RegisteredTaggedList
		{
			Tag = "a",
		};
		object expected = new RegisteredTaggedList
		{
			Tag = "b",
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Field Tag differed:
		                                                      Actual: "A!"
		                                                    Expected: "B!"
		                                                """).IgnoringNewlineStyle()
			.Because("the registered field is the one the collection declares itself, and reflection is not asked");
	}

	[Test]
	public async Task WhenListTypeIsRegisteredAsACollection_ShouldCompareTheRegisteredMembers()
	{
		RegisterShoutingList();
		object actual = new RegisteredList
		{
			Name = "a",
			Unregistered = "c",
		};
		object expected = new RegisteredList
		{
			Name = "b",
			Unregistered = "d",
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Property Name differed:
		                                                      Actual: "A!"
		                                                    Expected: "B!"
		                                                """).IgnoringNewlineStyle()
			.Because("the registered members are the ones the collection declares itself, and reflection is not asked");
	}

	[Test]
	public async Task WhenListsOfTheFrameworkDifferInCapacity_ShouldSucceed()
	{
		object actual = new List<int>(100)
		{
			1,
			2,
		};
		object expected = new List<int>(2)
		{
			1,
			2,
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsTrue()
			.Because("the capacity is declared by the framework list and describes the collection, not its content");
		await That(failureBuilder.ToString()).IsEmpty();
	}

	[Test]
	public async Task WhenSequenceTypeHasADifferentOwnMember_ShouldReportIt()
	{
		object actual = new SelfMadePage<int>("a", 2, 1, 2);
		object expected = new SelfMadePage<int>("b", 2, 1, 2);
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Property Name differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                """).IgnoringNewlineStyle();
	}

	[Test]
	public async Task WhenSequenceTypeHasEqualOwnMembers_ShouldSucceed()
	{
		object actual = new SelfMadePage<int>("a", 2, 1, 2);
		object expected = new SelfMadePage<int>("a", 2, 1, 2);
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsTrue();
		await That(failureBuilder.ToString()).IsEmpty();
	}

	[Test]
	public async Task WhenSequenceTypeImplementsAMemberOfAFrameworkInterface_ShouldNotCompareIt()
	{
		object actual = new SelfMadePage<int>("a", 5, 1, 2);
		object expected = new SelfMadePage<int>("a", 7, 1, 2);

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), new StringBuilder());

		await That(result).IsTrue()
			.Because("the Count implements the one of the framework interface, even though the type declares it");
	}

	[Test]
	public async Task WhenSequenceTypeIsAStruct_ShouldCompareItsOwnMembers()
	{
		object actual = new LabeledPair("a", 1, 2);
		object expected = new LabeledPair("b", 1, 2);
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse();
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Field Label differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                """).IgnoringNewlineStyle();
	}

	[Test]
	public async Task WhenSharedCollectionPairHasADifferentOwnMember_ShouldReportItForEveryPath()
	{
		ReadCounter counter = new();
		HeavyList actualShared = new(counter, "a");
		HeavyList expectedShared = new(counter, "b");
		object actual = new[]
		{
			actualShared, actualShared,
		};
		object expected = new[]
		{
			expectedShared, expectedShared,
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), failureBuilder);

		await That(result).IsFalse()
			.Because("equivalent items alone do not make the pair equivalent");
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Property [0].Name differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                and
		                                                  Property [1].Name differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                """).IgnoringNewlineStyle();
	}

	[Test]
	public async Task WhenSharedCollectionPairHasAnIgnoredOwnMemberOnOnePath_ShouldReportTheOtherPath()
	{
		ReadCounter counter = new();
		HeavyList actualShared = new(counter, "a");
		HeavyList expectedShared = new(counter, "b");
		object actual = new[]
		{
			actualShared, actualShared,
		};
		object expected = new[]
		{
			expectedShared, expectedShared,
		};
		EquivalencyOptions options = new()
		{
			MembersToIgnore = [new MemberToIgnore.ByName("[0].Name"),],
		};
		StringBuilder failureBuilder = new();

		bool result = await EquivalencyComparison.Compare(actual, expected, options, failureBuilder);

		await That(result).IsFalse()
			.Because("the pair is only equivalent on the path where its own member is ignored");
		await That(failureBuilder.ToString()).IsEqualTo("""

		                                                  Property [1].Name differed:
		                                                      Actual: "a"
		                                                    Expected: "b"
		                                                """).IgnoringNewlineStyle();
	}

	[Test]
	public async Task WhenSharedCollectionPairIsEquivalent_ShouldCompareItsOwnMembersOnce()
	{
		ReadCounter counter = new();
		HeavyList actualShared = new(counter, "a");
		HeavyList expectedShared = new(counter, "a");
		object actual = new[]
		{
			actualShared, actualShared, actualShared,
		};
		object expected = new[]
		{
			expectedShared, expectedShared, expectedShared,
		};

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), new StringBuilder());

		await That(result).IsTrue();
		await That(counter.Reads).IsEqualTo(2)
			.Because("the pair is remembered as equivalent with its items and its own members, which were read once on each side");
	}

	[Test]
	public async Task WhenUserCollectionHasNoOwnMembers_ShouldOnlyCompareTheItems()
	{
		object actual = new PlainList(100)
		{
			1,
			2,
		};
		object expected = new PlainList(2)
		{
			1,
			2,
		};

		bool result = await EquivalencyComparison.Compare(actual, expected, new EquivalencyOptions(), new StringBuilder());

		await That(result).IsTrue()
			.Because("neither its static member, its indexer nor the members of the framework list are its own members");
	}

	private static NamedList CreateNamedList(string name, params int[] items)
	{
		NamedList list = new()
		{
			Name = name,
		};
		list.AddRange(items);
		return list;
	}

	private static IEnumerable<int> Iterate(int value, int unused)
	{
		yield return value;
		if (unused < 0)
		{
			yield return unused;
		}
	}

	/// <remarks>
	///     The registered accessor differs from the property, so that a comparison shows which of them it used.
	/// </remarks>
	private static void RegisterShoutingList()
		=> TypeMetadataRegistry.RegisterBatch(() =>
		{
			TypeMetadataRegistry.RegisterProperty<RegisteredList, string>(nameof(RegisteredList.Name),
				o => o.Name.ToUpperInvariant() + "!");
			TypeMetadataRegistry.RegisterCollection<RegisteredList>();
		});

	private class NamedList : List<int>
	{
		public string Name { get; set; } = "";
		internal int Revision { get; set; }
	}

	private sealed class DescribedList : NamedList
	{
		public string Description { get; set; } = "";
	}

	private sealed class TaggedList : List<int>
	{
		public string Tag = "";
	}

	private sealed class RecountingList : List<int>
	{
		public new int Count { get; set; }
	}

	private sealed class RegisteredList : List<int>
	{
		public string Name { get; set; } = "";
		public string Unregistered { get; set; } = "";
	}

	private sealed class RegisteredTaggedList : List<int>
	{
		public string Tag = "";
	}

	private sealed class PlainList(int capacity) : List<int>(capacity)
	{
		public static string Shared { get; set; } = Guid.NewGuid().ToString();

		public string this[string key] => key + Capacity;
	}

	private sealed class ThrowingList(string message) : List<int>
	{
		public string Name => throw new InvalidOperationException(message);
	}

	private sealed class NamedLookup : Dictionary<string, int>
	{
		public string Name { get; set; } = "";
	}

	/// <summary>
	///     Its <see cref="IsReadOnly" /> overrides the one of the framework list and differs for the same items.
	/// </summary>
	private sealed class FlaggedList(bool isReadOnly) : ArrayList
	{
		public override bool IsReadOnly => isReadOnly;
	}

	/// <summary>
	///     Has enough items to be remembered once it was found equivalent.
	/// </summary>
	private sealed class HeavyList : List<WithProperty>
	{
		private readonly ReadCounter _counter;
		private readonly string _name;

		public HeavyList(ReadCounter counter, string name)
		{
			_counter = counter;
			_name = name;
			AddRange(Enumerable.Range(0, 100).Select(i => new WithProperty(i)));
		}

		public string Name
		{
			get
			{
				_counter.Reads++;
				return _name;
			}
		}
	}

	private sealed class ReadCounter
	{
		public int Reads { get; set; }
	}

	/// <summary>
	///     Implements the sequence itself, and its <see cref="Count" /> for the interface of the framework, which
	///     says nothing about the number of its items.
	/// </summary>
	private sealed class SelfMadePage<T>(string name, int count, params T[] items) : IReadOnlyCollection<T>
	{
		public string Name { get; } = name;

		public int Count { get; } = count;

		public IEnumerator<T> GetEnumerator() => ((IEnumerable<T>)items).GetEnumerator();

		IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
	}

	private sealed class SelfMadeLookup(string name, int count, Dictionary<string, int> entries)
		: IReadOnlyDictionary<string, int>
	{
		public string Name { get; } = name;

		public int this[string key] => entries[key];

		public IEnumerable<string> Keys => entries.Keys.Concat([Name,]);

		public IEnumerable<int> Values => entries.Values.Concat([Count,]);

		public int Count { get; } = count;

		public bool ContainsKey(string key) => entries.ContainsKey(key);

		public bool TryGetValue(string key, out int value) => entries.TryGetValue(key, out value);

		public IEnumerator<KeyValuePair<string, int>> GetEnumerator() => entries.GetEnumerator();

		IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
	}

	private readonly struct LabeledPair(string label, params int[] items) : IEnumerable<int>
	{
		public readonly string Label = label;

		public IEnumerator<int> GetEnumerator() => ((IEnumerable<int>)items).GetEnumerator();

		IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
	}
}
