<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="TUnit"/>
		<PackageReference Include="Microsoft.Testing.Extensions.TrxReport"/>
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Source\aweXpect.Generators\aweXpect.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
		<ProjectReference Include="..\..\..\Source\aweXpect\aweXpect.csproj"/>
	</ItemGroup>

</Project>
