//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aweXpect.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aweXpect.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Await the expectation.
        /// </summary>
        internal static string aweXpect0001CodeFixTitle {
            get {
                return ResourceManager.GetString("aweXpect0001CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to evaluate an expectation it must either be awaited or explicitly verified at the end..
        /// </summary>
        internal static string aweXpect0001Description {
            get {
                return ResourceManager.GetString("aweXpect0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expectations must be awaited or verified.
        /// </summary>
        internal static string aweXpect0001MessageFormat {
            get {
                return ResourceManager.GetString("aweXpect0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expectations must be awaited or verified.
        /// </summary>
        internal static string aweXpect0001Title {
            get {
                return ResourceManager.GetString("aweXpect0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method object.Equals is not supported for the expectations. You should use &quot;IsEqualTo&quot; instead!.
        /// </summary>
        internal static string aweXpect0002Description {
            get {
                return ResourceManager.GetString("aweXpect0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace &quot;Equals&quot; with &quot;IsEqualTo&quot;.
        /// </summary>
        internal static string aweXpect0002MessageFormat {
            get {
                return ResourceManager.GetString("aweXpect0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace &quot;Equals&quot; with &quot;IsEqualTo&quot;.
        /// </summary>
        internal static string aweXpect0002Title {
            get {
                return ResourceManager.GetString("aweXpect0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directly after &quot;Throws&quot; the expectation continues the sentence &quot;throws a …&quot;, so it must use the nested &quot;With…&quot; vocabulary. The &quot;Has…&quot; vocabulary starts a standalone sentence about an exception and belongs after &quot;.Which&quot; (or on an exception subject). Using it directly after &quot;Throws&quot; produces an ungrammatical failure message..
        /// </summary>
        internal static string aweXpect0003Description {
            get {
                return ResourceManager.GetString("aweXpect0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert &quot;.Which&quot;.
        /// </summary>
        internal static string aweXpect0003InsertWhichCodeFixTitle {
            get {
                return ResourceManager.GetString("aweXpect0003InsertWhichCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace &quot;{0}&quot; with &quot;{1}&quot; or insert &quot;.Which&quot; before it.
        /// </summary>
        internal static string aweXpect0003MessageFormat {
            get {
                return ResourceManager.GetString("aweXpect0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with &quot;{0}&quot;.
        /// </summary>
        internal static string aweXpect0003ReplaceCodeFixTitle {
            get {
                return ResourceManager.GetString("aweXpect0003ReplaceCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &quot;With…&quot; instead of &quot;Has…&quot; directly after &quot;Throws&quot;.
        /// </summary>
        internal static string aweXpect0003Title {
            get {
                return ResourceManager.GetString("aweXpect0003Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert &quot;.DoesNotThrow().WhoseResult&quot;.
        /// </summary>
        internal static string aweXpect0004CodeFixTitle {
            get {
                return ResourceManager.GetString("aweXpect0004CodeFixTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A delegate subject is wrapped, so an expectation that is written for an object binds to the wrapper instead of to what the delegate does: it silently passes, fails with a message about the delegate, or throws at runtime. Continue with &quot;DoesNotThrow().WhoseResult&quot; to make the expectation about the returned value, or await the delegate expectation to obtain that value. A delegate without a return value has nothing to compare, so state what it should do with &quot;DoesNotThrow&quot;, &quot;Throws&quot; or &quot;ExecutesIn&quot;; to make an [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aweXpect0004Description {
            get {
                return ResourceManager.GetString("aweXpect0004Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is applied to the delegate itself instead of to its execution.
        /// </summary>
        internal static string aweXpect0004MessageFormat {
            get {
                return ResourceManager.GetString("aweXpect0004MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expectations for an object must not be applied to a delegate subject.
        /// </summary>
        internal static string aweXpect0004Title {
            get {
                return ResourceManager.GetString("aweXpect0004Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The subject was verified to be not null by a preceding expectation..
        /// </summary>
        internal static string IsNotNullSuppressionJustification {
            get {
                return ResourceManager.GetString("IsNotNullSuppressionJustification", resourceCulture);
            }
        }
    }
}
